### ISSUE TITLE
Where to pass `data` field in transaction?

### ISSUE THREAD

**Issue by Confucian-e** [Rubilmax/viem-tracer#1]
## Feature Request

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

## Are you willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time, and I know how to start.
- [ ] Yes, I have the time, but I don't know how to start. I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by Rubilmax** [comment]
Hi, you can either:
- pass `data` as a field of `traceCall` parameter (just like a call or a tx using viem); OR
- use regular viem functions like `client.writeContract` or `client.sendTransaction`

**Comment by Rubilmax** [comment]
I added a concrete example in https://github.com/Rubilmax/viem-tracer/commit/57d7ff08c2398b533eaf6f571de5c08218874e34
