### ISSUE TITLE
`logs` property?

### ISSUE THREAD

**Issue by kyscott18** [Rubilmax/viem-tracer#2]
More of a question, but what's the expected behavior of the `logs` property in return type?

https://github.com/Rubilmax/viem-tracer/blob/main/src/actions/traceCall.ts#L59

I can see other libraries that have this type, but haven't seen a response with it defined.

https://github.com/alloy-rs/alloy/blob/main/crates/rpc-types-trace/src/geth/call.rs#L39

**Comment by Rubilmax** [comment]
Hi! I don't know either unfortunately, I only copied the type from geth

Maybe it is the array of events emitted in raw form
